powerVCF.psm1
Get-VCFBackupConfiguration
Get-VCFBundles
Get-VCFCertificateAuthConfiguration
Get-VCFDepotCredentials
Set-VCFDepotCredentials
Get-VCFManagers
Get-VCFServices
=> Adding New Modules

powerVCF.psm1
Function to check VCF Version, used Get-VCFManager cmdlet and then checks for 3.9
=> Added CheckVCFVersion

README.md, powerVCF.psm1
Get-VCFvCenter
Get-VCFnsxvManager
Get-VCFnsxtCluster
Minor tweaks for examples on:
Get-VCFManager
Get-VCFService
=> New Modules 'Foundation Component'

powerVCF.psm1
Added function Get-VCFPSC
implemented SkipCertificateCheck on Connect-VCFManager for PS CORE
=> New function + enhanced Connect-VCFManager

powerVCF.psm1
created Start-VCFBackup function. Tested and working fine but at present I am not monitoring for the task completion, so it is async. Using Get-VCFTask we can subsequently see the task end status.
=> added Start-VCFBackup function

powerVCF.psm1
Updated Validate-CommissionHostSpec to generate the json format required for the validation API.
=> Updated Validate-CommissionHostSpec

powerVCF.psm1
Update validation functions to generate validation json spec
=> Update validation functions

SampleJSON/Host/vcf-s1-2-nodes-commissionSpecs.json, SampleJSON/Host/vcf-s1-3-nodes-commissionSpecs.json, powerVCF.psm1
Enhancing Commission-VCFHost so that it checks how the JSON validation task completed
=> updating Commission-VCFHost with status checks

powerVCF.psm1
Added ability to get details of single bundle by passing the ID
Moved Start-VCFBackup into section for Backup Operations
=> Enhancement to Get-VCFBundle

powerVCF.psm1
Module to immediatly download a bundle from the depot
=> Added Update-VCFBundle

SampleJSON/Certificates/requestCsrSpec.json, powerVCF.psm1
Get-VCFCertificateCSRs
Request-VCFCertificateCSRs
=> Add CSR Functions

powerVCF.psm1
Added some new modules for manipulating IP Pools within Network Pools
- Get-VCFNetwork
- Add-VCFNetwork
- Remove-VCFNetwork
=> Dev 39 gjb ip pools

README.md, SampleJSON/LicenseKey/addLicenseKeySpec.json
Added some markdown formatting, fixed a few typos, and added additional values for license keys in spec.
=> Update README and add additional license specs

SampleJSON/Certificates/requestCertificateSpec.json, SampleJSON/Certificates/updateCertificateSpec.json, powerVCF.psm1
Updated Sample JSON files for Certificates
Updated the example for Update-VCFCertificate to reference the correct Sample JSON
=> Dev 39 gjb certs

docs/functions/Host/Reset-VCFHost.md, powerVCF.psm1
New function Reset-VCFHost which is executing SoS --cleanup-host
=> Reset-VCFHost

powerVCF.psm1
Added missing $response return on the following functions:
- Validate-VCFClusterSpec
- Validate-VCFUpdateClusterSpec
=> $response return on Validate functions

docs/functions/CEIP/Get-VCFCeip.md, docs/functions/CEIP/Set-VCFCeip.md, powerVCF.psm1
Made some formatting changes across CEIP modules for consistency
Added example to Set-VCFCeip
Fixed type in Set-VCFCeip Function
=> Formatting for CEIP Modules

docs/functions/Certificates/Get-VCFCertificate.md, docs/functions/Certificates/Get-VCFCertificateAuthConfiguration.md, docs/functions/Certificates/Get-VCFCertificateCSR.md, docs/functions/Certificates/Request-VCFCertificate.md, docs/functions/Certificates/Request-VCFCertificateCSR.md, docs/functions/Certificates/Set-VCFCertificate.md, docs/functions/Connect-VCFManager.md, docs/functions/Foundation/Get-VCFManager.md, docs/functions/Foundation/Get-VCFPSC.md, docs/functions/Foundation/Get-VCFService.md, docs/functions/Foundation/Get-VCFnsxtCluster.md, docs/functions/Foundation/Get-VCFnsxvManager.md, docs/functions/License Key/Get-VCFLicenseKey.md, powerVCF.psm1
Performed some formatting consistency across modules
Added a few input validations
Renamed a number of modules to follow Upper/Lower case format and removed 's' from a couple
Rename Get-VCFPSC to Get-VCFPsc
Rename Get-VCFnsxvManager to Get-VCFNsxvManager
Rename Get-VCFnsxtCluster to Get-VCFNsxtCluster
Rename Get-VCFCertificateCSRs to Get-VCFCertificateCSR
Rename Request-VCFCertificateCSRs to Request-VCFCertificateCSR
=> Various Formatting Updates & a few Module Renames

docs/functions/Connect-VCFManager.md, docs/functions/Credentials/Get-VCFCredential.md, docs/functions/Foundation/Get-VCFManager.md, docs/functions/Foundation/Get-VCFPSC.md, docs/functions/Foundation/Get-VCFnsxtCluster.md, docs/functions/Foundation/Get-VCFnsxvManager.md, docs/functions/Foundation/Get-VCFvCenter.md, powerVCF.psm1
Updated Get-VCFNsxtCluster
Updated Get-VCFNsxvManager
Updated Get-VCFPsc
Updated Get-VCFvCenter
Updated Connect-VCFManager
Updated Get-VCFService
Fixed Type in Get-VCFCredential Doc
=> Enhancements and Code Reduction

SampleJSON/SystemCheck/precheckVCFSystem.json, powerVCF.psm1
Fixed Spelling mistake - ResponseException in 3 functions 1)Get-VCFCredentialTask 2) Get-VCFCredentialTask 3) Retry-VCFCredentialTask
=> Dev vcf 40 kb cred syscheck

SampleJSON/Federation/createFederation.json, docs/functions/Federation/Get-VCFFederation.md, docs/functions/Federation/Remove-VCFFederation.md, docs/functions/Federation/Set-VCFFederation.md, docs/functions/Tasks/Get-VCFTask.md, docs/functions/Workload Domain/Get-VCFWorkloadDomain.md, powerVCF.psm1
- Code Clean Up and Formatting
- New Internal Function createHeader
- New cmdlet Set-VCFFederation
- New Docs for some existing Federation cmdlets
=> Various Changes

docs/functions/Backup/Get-VCFBackupConfiguration.md, docs/functions/Backup/Set-VCFBackupConfiguration .md, powerVCF.psm1
Fixed response to handle formatting ($response.backupLocations)
Updated Description and Example Details
=> Get-VCFBackupConfiguration

SampleJSON/Bundle/bundleUploadspec.json, docs/functions/Bundles/Start-UPloadVCFBundle.md, powerVCF.psm1
Cmdlet for uploading bundles offline onto SDDC manager.
1. Cmdlet Start-UploadVCFBundle added
2. sample spec bundleUploadspec.json
3. Start-UPloadVCFBundle.md
=> Added cmdlet for uploading bundles

docs/functions/Certificates/Get-VCFCertificate.md, powerVCF.psm1
Updated the $response.elements to improve the format of the output
Added Example using Select issuedTo
=> Get-VCFCertificate

SampleJSON/Edge Cluster/edgeClusterSpec.json, docs/functions/NSX-T Edge Clusters/New-VCFEdgeCluster.md, powerVCF.psm1
Added New-VCFEdgeCluster with inline validation, doc & sample JSON
=> Added New-VCFEdgeCluster

powerVCF.psm1
SoS Clean Up has been removed from VCF 4.0
=> Remove Reset-VCFHost

powerVCF.psm1
Please give this a test. It worked for me just now whereas the code being replaced waited for 5 seconds and then failed out because the validation was still ongoing.
=> Dev 400 edgecluster fix

PowerVCF.psm1
Updated checkVCFToken to handle cmdlets being run when no token exists
=> Updated checkVCFToken

PowerVCF.psm1, docs/functions/Users/Get-VCFUser.md, docs/functions/Users/New-VCFGroup.md
- Added New-VCFGroup cmdlet
- Added -type to Get-VCFUser
- Added -domain to Get-VCFUser
=> Enhancements to Users and Groups

PowerVCF.psm1
=> Revert "reponse handling"

PowerVCF.psm1
Fix issue with checking and reading the Json before triggering the workflow
=> Set-VCFFederation

PowerVCF.psm1
* Fix indent
* use ValidateSet for status parameter
* use ParameterSetName for parameter
=> Enhance Get-VCFHost

PowerVCF.psm1
i use 4 spaces indent
add also add .vscode settings
=> Fix indent using Visual Code Formatter 

CHANGELOG.md, PowerVCF.psm1
- Renamed Set-VCFvRLI to Set-VCFvRLIConnection
- Added Get-VCFvRLIConnection
=> Get/Set-VCFvRLIConnection - Resolves #127

CHANGELOG.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE, PowerVCF.psm1, docs/functions/vRealize Operations Manager/Get-VCFvROPSConnection.md, docs/functions/vRealize Operations Manager/Get-VCFvROPs.md, docs/functions/vRealize Operations Manager/Set-VCFvROPSConnection.md
- Renamed Set-VCFvRLI to Set-VCFvRLIConnection
- Added Get-VCFvRLIConnection
- Added CODE_OF_CONDUCT.md
- Added LICENSE
- Added CONTRIBUTING.md
=> Get\Set-VCFvROPSConnection (Resolves #132)

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/docs.yml, .github/ISSUE_TEMPLATE/enhancement.yml, .github/comment_template.md, .github/pull_request_template.md, .github/workflows/issue-greeting.yml, .github/workflows/lock-threads.yml, .github/workflows/pull-request-sizing.yml, .github/workflows/pull-request-status.yml, .github/workflows/stale.yml, CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE, NOTICE, README.md
Project community health file update prior to request to move to a VMware GitHub organization:
- UPDATES `README.md`
- Updates `CODE_OF_CONDUCT.md`
- Updates `CONTRIBUTING.md`
- Adds `CODEOWNERS` for code reviews.
- Updates `LICENSE`
- Adds issue and pull request templates.
- Adds actions for issue greeting, status, and thread locking.
- Adds actions for relative sizing of pull requests.
- Adds `NOTICE`
=> Update project community health

PowerVCF.psm1, SampleJSON/SOS/supportBundle.json, SampleJSON/SOS/systemHealthChecks.json, docs/functions/SoS Functions/Get-VCFHealthSummaryTask.md, docs/functions/SoS Functions/Get-VCFSupportBundleTask.md, docs/functions/SoS Functions/Request-VCFHealthSummaryBundle.md, docs/functions/SoS Functions/Request-VCFSupportBundle.md, docs/functions/SoS Functions/Start-VCFHealthSummary.md, docs/functions/SoS Functions/Start-VCFSupportBundle.md
Added New cmdlets:
- Get-VCFHealthSummaryTask
- Request-VCFHealthSummaryBundle
- Start-VCFHealthSummary
- Get-VCFSupportBundleTask
- Request-VCFSupportBundle
- Start-VCFSupportBundle
Added Sample JSON Specs
- systemHealthChecks.json
- supportBundle.json
Added Documentation
Closes #137 
Signed-off-by: Gary Blake <gblake@vmware.com>
=> API for managing SOS

PowerVCF.psm1
Adds -status option to Get-VCFCredentialTask
[ ] This is a bugfix.
[X] This is an enhancement or feature.
[ ] This is a code style / formatting update.
[ ] This is a documentation update.
[ ] This is a refactoring update.
[ ] This is something else.
Signed-off-by: Gary Blake <gblake@vmware.com>
=> Enhance: Add -status to Get-VCFCredentialTask

PowerVCF.psm1
- Added skipCertificateCheck
- Remove alias for Connect-VCFToken
- [ X ] This is an enhancement or feature.
Signed-off-by: Gary Blake <gblake@vmware.com>
=> Enhance: Request-VCFToken / Connect-CloudBuilder

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/enhancement.yml
Updates the URLs to the project `CODE_OF_CONDUCT.md` in the issue templates.
Please describe: `chore`
=> chore: update issue templates

PowerVCF.psm1
Update the following to more closely align with the related projects:
- Contributing text and URL.
- Disclaimer text.
- Self-signed certificates text.
=> fix: update module frontmatter

PowerVCF.psm1
Add support for the FIPS Mode API introduced in 4.3.0.
This API can returns the status of the FIPS Mode security configuration for the VMware Cloud Foundation instance.
Issue Number: Closes #171
=> feat: add support for fips mode api

PowerVCF.psm1
Adds support for the Releases API with the `Get-VCRelease` cmdlet.
Issue Number: Closes #168
=> feat: add support for releases api

PowerVCF.psd1
Adds additional metadata to PowerShell Gallery listing:
- Tags
- Project URL
- License URL
- Release Notes URL (Changelog)
- Icon URL
> **Note**
>
> I have not updated the metadata version to 2.3.0 yet. We should consider adding a build number, such as: `2.3.0.1001, for the next release.
Issue Number: Closes #175
```powershel
PS /Users/johnsonryan/.../Code/Work/PowerVCF> test-ModuleManifest ./PowerVCF.psd1
ModuleType Version    PreRelease Name                                ExportedCommands
---------- ------- …
```
=> feat: add module metadata

PowerVCF.psm1
Add the option to both get and set the Dell EMC Support account credentials using a `-vxrail` switch, without breaking changes.
```powershell
Get-VCFDepotCredential -vxrail
```
```powershell
Set-VCFDepotCredential -vxrail -username support@rainpole.io -password VMw@re1!
```
Closes: #177
=> feat: add option for dell emc support account

PowerVCF.psd1
Removes spaces from tags metadata that would error a release.
- `VMware`
- `CloudFoundation`
- `VMwareCloudFoundation`
=> fix: update module metadata

PowerVCF.psm1
Updates the `Get-VCFvRLI` cmdlet .SYNOPSIS which was causing an issue with the `VMware.CloudFoundation.Reporting` overview report results.
=> fix: update `Get-VCFvRLI` cmdlet synopsis

CHANGELOG.md, PowerVCF.psd1, PowerVCF.psm1
- Added `Get-VCFCredentialExpiry` cmdlet to retrieve the password expiry details for credentials.
- Updated PowerVCF.psm1 version
- Updated CHANGELOG.md
Issue Number: Closes #185
=> feat: add support for retrieve credential expiry details

CHANGELOG.md, PowerVCF.psd1, PowerVCF.psm1, content/en/docs/functions/License Key/Get-VCFLicenseMode.md, content/en/docs/functions/Personality/New-VCFPersonality.md
Adding cmdlet to retrieve the license mode (subscription or perpetual)
Adding cmdlet to retrieve the license mode (subscription or perpetual)
no
=> feat: add `Get-VCFLicenseMode` cmdlet

.github/workflows/pages.yml
Working to resolve GitHub Action failure for Hugo:
- Updates Hugo from v0.99.0 to v0.111.3 in GitHub Action.
Please describe: `chore`
=> chore(deps): bump hugo from v0.99.0 to v0.111.3

.github/workflows/pages.yml
Updates Hugo binary from Linux-64bit.deb to linux-amd64.deb.
=> fix: gha action hugo binary

.github/workflows/pages.yml
Updates action based on Docsy documentation and requirement for PostCSS.
Ref: https://www.docsy.dev/docs/get-started/docsy-as-module/installation-prerequisites/#install-postcss
=> fix: gha action hugo

CHANGELOG.md, PowerVCF.psd1, PowerVCF.psm1
- Updated `Request-VCFToken` cmdlet exception error handling.
- Updated `CHANGELOG.md`.
- Updates the module metadata from v2.3.0.1004 to v2.4.0.1000.
Ref: #187
Closes #187 
Update `Request-VCFToken` to use the module's `ResponseException` function: 
```powershell
Catch {
ResponseException -object $_
}
```
Example: HTTP 401
```powershell
PS F:\VMware.CloudFoundation.Reporting> Request-VCFToken -fqdn sfo-vcf01.sfo.rainpole.io -username administrator@vsphere.local -password ThisIsNotTheCorrectPassword
Script File:        Line: 68
Relevant Command:  $response = …
```
=> fix: update exception error handling

.github/workflows/deploy.yml, .github/workflows/issue-greeting.yml, .github/workflows/lock-threads.yml, .github/workflows/pull-request-sizing.yml, .github/workflows/stale.yml
Pin actions to a full length commit SHA.
Ref: [Security hardening for GitHub Actions](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions)
Please describe: `chore`
=> chore(gha): pin actions to commit sha

CHANGELOG.md, PowerVCF.psd1, PowerVCF.psm1, docs/documentation/functions/sddc-managers/Get-VCFManager.md
- Enhanced `Get-VCFManager` cmdlet to return the SDDC Manager version in `x.y.z` format.
- Enhanced `Get-VCFManager` cmdlet to return the SDDC Manager build in `xxxxxxx` format.
- Updated the documentation for `Get-VCFManager` cmdlet.
- Updated the GUID to be a correct validated GUID.
- Modified API warning messages.
```powershell
PS C:\Users\Administrator> Get-VCFManager
domain    : @{id=c2e23a9e-986d-49a9-964d-a613d389deeb}
id        : f1a7ba83-301d-45fc-bddc-fdd4247858fe
fqdn      : sfo-vcf01.sfo.rainpole.io
version   : 4.5.1.0-21682411
ipAddress : …
```
=> feat: enhance `Get-VCFManager` to return version or build

.ci/pester.tests.ps1, .github/workflows/ci-module.yml
Adds **basic** CI checks for module import and manifest check when changed are made to `.psm1` and `.psd1` files only.
Please describe: ci
=> ci(module): add basic module ci

CHANGELOG.md, PowerVCF.psd1, PowerVCF.psm1
Fixed `validateJsonInput` to prevent it from truncating directly passed JSON content.
Tested using JSON content previously failing during a `Set-VCFCredential` operation.
=> fix: update `validatejsoninput` function

.github/workflows/deploy.yml
Updates the GitHub Action for Mkdocs to run after a release or on workflow dispatch (manual start) and by default run on the release tag.
=> chore(ci): update mkdocs actions

docs/documentation/getting-started/install.md, docs/snippets/copy-module-local-linux.sh, docs/snippets/copy-module-local-windows.ps1, docs/snippets/import-module-local-linux.ps1, docs/snippets/pre-req-linux.sh, docs/snippets/save-module-local-linux.ps1, docs/snippets/save-module-local-windows.ps1
Adding documentation to install modules and dependencies in a air-gapped environment.
=> docs: add air-gapped install 

docs/snippets/save-module-local-windows.ps1
Updated Save Module to remove Import-Module and change to Save-Module
Updated Save Module to remove Import-Module and change to Save-Module
=> docs: update air-gapped steps
